version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ec2-user
